import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans, Roboto, Inter } from "next/font/google";
import "./globals.css";
import { TranslationProvider } from "./context/TranslationContext";
import { ThemeProvider } from "next-themes";
import { AppProvider } from "./context/AppContext";
import Head from "next/head";
import Link from "next/link";
// import { Open_Sans } from "next/font/google";

// const openSans = Open_Sans({
//   subsets: ["latin"],
//   weight: ["400", "700"],
//   variable: "--font-open-sans",
// });

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "700", "800", "900"],
  variable: "--font-roboto",
  display: "swap",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "700", "800", "900"],
  variable: "--font-roboto",
});

const geistMono = Geist_Mono({
  // variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Book Haven",
  description: "Generated by create next app",
  icons: {
    icon: "/book-opened-svgrepo-com.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Head>
        <Link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head> */}
      <body className={`bg-light-black ${inter.variable}`}>
        <ThemeProvider attribute="class">
          <AppProvider>
            <TranslationProvider>{children}</TranslationProvider>
          </AppProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
