import type { Metadata } from "next";
import "@/styles/globals.css";

export const metadata: Metadata = {
    title: "Book Haven",
    description: "Generated by create next app",
    icons: {
        icon: "/book-opened-svgrepo-com.svg",
    },
};

export default function BookDetailsLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                {children}
            </body>
        </html>
    );
}
