import Footer from "@/components/layout/Footer/Footer"
import NavBar from "@/components/layout/NavBar/NavBar"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function MarketingLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <NavBar />
                {children}
                <Footer />
            </body>
        </html>
    )
}
